routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/app/login', ['uses' => 'JwtAuthenticateController@appLogin', 'as' => 'app.login']);
Route::get('/app/logout', 'JwtAuthenticateController@logout')->name('app.logout');
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['ability:admin|destination,create-users'], 'as' => 'admin.'], function () {
    // Protected route
    Route::get('select_branch', 'DashboardController@selectBranch')->name('select_branch');
    Route::get('notifications/view_all', 'UserController@viewNotifications')->name('notification.view_all');
    Route::get('notifications/query', 'UserController@queryNotifications')->name('notification.query');
    Route::get('/bill-record', 'UserController@billRecord')->name('billRecord');
    Route::get('/bill-record/{id}/profile', 'UserController@billProfile')->name('bill_record.profile');
    Route::get('/bill-record/cancel', 'UserController@cancelBill')->name('billRecord.cancel');
    Route::post('/bill-record-store', 'UserController@storeBillRecord')->name('billRecord.store');
    Route::get('/bill-record-list', 'UserController@listBillRecord')->name('billRecord.list');
    Route::get('/bill-record-list/{id}/edit', 'UserController@editBillRecord')->name('billRecord.edit');
    Route::post('/bill-record-list/update', 'UserController@updateBillRecord')->name('billRecord.update');
    Route::get('/bill-record-list/delete', 'UserController@deleteBillRecord')->name('billRecord.delete');
    Route::get('dashboard', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);
    Route::post('/branch_para/import', 'BranchparaController@import')->name('branch_para.import');
    Route::resource('/branch_para', 'BranchparaController');
    Route::post('/package/updateDetail', 'UserController@updatePackage')->name('package.update_detail');
    Route::get('/package/{id}/edit', 'UserController@editPackage');
    Route::delete('/package/{id}/deletePackage', 'UserController@deletePackage');
    Route::get('/package', 'UserController@package')->name('package');
    Route::post('/package', 'UserController@packageStore')->name('package.store');
    Route::post('/category/updateDetail', 'UserController@updateItem')->name('category.update_detail');
    Route::get('/category/{id}/edit', 'UserController@editItem');
    Route::delete('/category/{id}/deleteItem', 'UserController@deletePackage');
    Route::get('/category', 'UserController@itemCategory')->name('category');
    Route::post('/category', 'UserController@itemCategoryStore')->name('category.store');
    Route::get('/user/add', 'UserController@addUser')->name('user.add');
     Route::get('/user/status_change', 'UserController@statusChange')->name('user.status_change');
    Route::get('/user/search_query','UserController@searchQuery')->name('user.search_query');
    Route::get('/user/profile/{id}','UserController@profile')->name('user.profile');
    Route::get('/user/member/selected', 'UserController@memberSelected')->name('user.member.selected');
    Route::post('/user/store', 'UserController@storeUser')->name('user.store');
    Route::get('/user/package/selected', 'UserController@selectedPackage')->name('user.package.selected');
    Route::get('/user/list', 'UserController@userList')->name('user.list');
    Route::get('/user/bill_detail/{id}', 'UserController@billDetail')->name('user.bill_detail');
    Route::get('/user/{id}/edit', 'UserController@editUser')->name('user.edit');
    Route::post('/user/updateDetail', 'UserController@updateUser')->name('user.updateDetail');
    Route::get('/user/cash_entry', 'UserController@cashEntry')->name('user.cash_entry');
    Route::post('/user/cash_entry', 'UserController@cashEntryPost')->name('user.cash_entry.store');
    Route::get('/user/cash_entry/list', 'UserController@cashEntryList')->name('user.cash_entry.list');
    Route::get('/user/cash_entry/list/{id}/edit', 'UserController@editCashEntryList')->name('user.cash_entry.list.edit');
    Route::post('/user/cash_entry/list/update', 'UserController@updateCashEntryList')->name('user.cash_entry.list.update');
    Route::get('/user/cash_entry/list/delete', 'UserController@deleteCashEntryList')->name('user.cash_entry.list.delete');
     Route::get('/user/cash_entry/monthlylist', 'UserController@monthlylist')->name('user.cash_entry.monthlylist');
    Route::post('/user/cash_entry/query', 'UserController@cashEntryQuery')->name('user.cash_entry.query');
    Route::get('/user/query', 'UserController@query')->name('user.query');
    Route::get('/user/bank_account', 'UserController@bankAccount')->name('user.bank_account');
    Route::post('/user/bank_account', 'UserController@bankEntryStore')->name('user.bank_account.store');
    Route::get('/user/bank_account/list', 'UserController@bankAccountList')->name('user.bank_account.list');
    Route::get('/user/bank_account/list/delete', 'UserController@deleteBankAccountList')->name('user.bank_account.list.delete');
    Route::get('/user/bank_account/list/{id}/edit', 'UserController@editBankAccountList')->name('user.bank_account.list.edit');
    Route::post('/user/bank_account/list/update', 'UserController@updateBankAccountList')->name('user.bank_account.list.update');
    Route::get('/user/bank_account/query', 'UserController@bankAccountQuery')->name('user.bank_account.queryList');
    Route::post('/user/bank_account/query', 'UserController@bankEntryQuery')->name('user.bank_account.query');
    Route::get('/user/valid_date','UserController@validDate')->name('user.valid_date');
    Route::group(['prefix' => 'utility', 'as' => 'utility.'], function () {
        Route::get('bill_issue', ['uses' => 'UtilityController@billIssueIndex', 'as' => 'bill_issue']);
        Route::post('bill_issue', ['uses' => 'UtilityController@billIssueStore', 'as' => 'bill_issue']);
    });
    Route::post('user/import','UserController@import')->name('user.import');


});

resources/views/admin/category/index.blade.php
@extends('admin.admin_layout.layout')
@section('content')
    <?php $token = Session::get('token'); ?>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Dashboard
                <small>Control panel</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
            @include('flash.message')
            <!-- left column -->
                <div class="col-md-4">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Item</h3>
                        </div>

                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" id="branch_para_submit">
                            {!! csrf_field() !!}
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Name</label>

                                    <input type="text" class="form-control" id="exampleInputPassword1"
                                           placeholder="Item name" name="item_name" required>


                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Price</label>
                                    <input type="number" class="form-control" id="exampleInputPassword1"
                                           placeholder="Price" name="price" required>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->


                </div>
                <div class="col-md-8">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Item List</h3>
                        </div>
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>SNo</th>
                                <th>Item Category</th>
                                <th>Price</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $i = 1; ?>
                            @foreach($items as $p)
                                <tr>
                                    <td>{{$i++}}</td>
                                    <td>{{$p->item_name}}</td>
                                    <td>{{$p->price}}</td>
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn btn-default dropdown-toggle" type="button"
                                                    data-toggle="dropdown">Action
                                                <span class="caret"></span></button>
                                            <ul class="dropdown-menu">
                                                <li><a href="#" data-id="{{$p->id}}" class="btn-edit">Edit</a>
                                                </li>
                                                <li><a href="#" data-id="{{$p->id}}"
                                                       class="btn-delete">Delete</a></li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tfoot>
                        </table>
                    </div>
                </div>
                <!--/.col (left) -->
                <!-- right column -->

                <!--/.col (right) -->
            </div>

        </section>
    </div>
    <!-- Modal -->

    <div id="myModal2" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="edit-branch">
                    <div class="box box-primary">
                        <form role="form" id="update_package">
                            {!! csrf_field() !!}
                            <div class="box-header with-border">
                                <h3 class="box-title">Edit Package</h3>
                            </div>
                            <div class="box-body">
                                <input name="item_id" type="hidden">
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Name</label>

                                    <input type="text" class="form-control" id="exampleInputPassword1"
                                           placeholder="Item name" name="item_name" required>


                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Price</label>
                                    <input type="number" class="form-control" id="exampleInputPassword1"
                                           placeholder="Price"
                                           name="price" required>
                                </div>
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div id="myModal3" class="modal custom fade">
        <div class="modal-dialog" role="document">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete Information</h5>
                </div>
                <form action="#" method="Post" id="delete_package">
                    {!! csrf_field() !!}
                    <div class="modal-body">
                        <input name="info_id" type="hidden"/>

                        <p>Are you sure to delete this information?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Delete</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            var base_url = "{{url('/')}}";
            <!--edit-->
            $('#example1').on('click', '.btn-edit', function () {
                $.ajax({
                    url: base_url + '/admin/category/' + $(this).attr('data-id') + '/edit',
                    method: "GET",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
                    },
                    data: $(this).serialize(),
                    success: function (response) {
                        $('#myModal2').modal('show');
                        // $('option:selected', 'select[name="month_pop"]').removeAttr('selected');
                        // $('[name="month_pop"]').find('option[value=' + response.data.package.month + ']').attr('selected', 'selected');
                        $('#update_package').find('[name="price"]').val(response.data.item.price);
                        $('#update_package').find('[name="item_name"]').val(response.data.item.item_name);
                        $('[name="item_id"]').val(response.data.item.id);
                    }
                })
            });
            $('#update_package').submit(function (e) {
                e.preventDefault();
                $.ajax({
                    url: "{{route('admin.category.update_detail')}}",
                    method: "POST",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
                    },

                    data: $(this).serialize(),
                    success: function (response) {
                        location.reload();
                    }

                })
            });

            $('#branch_para_submit').submit(function (e) {
                e.preventDefault();
                $.ajax({
                    url: "{{route('admin.category.store')}}",
                    method: "POST",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
                    },
                    data: $(this).serialize(),
                    success: function (response) {
                        console.log(response);
                        location.reload();
                        // $('.api_error_message').html('<div class="alert alert-success alert-dismissible"> <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> <h4><i class="icon fa fa-ban"></i>Success!</h4>'+response.message+' </div>');


                    }
                })
            });
            $('#branch_para_submit').keyup(function (event) {

                if (event.keyCode === 112) {
                    $('.submit_click').click();

                }
            });

            <!--delete-->
            $('#example1').on('click', '.btn-delete', function (e) {
                var delete_id = $(this).attr('data-id');
                $('#myModal3').modal('show');
                $('[name="info_id"]').val(delete_id);

            });
            $('#delete_package').on('submit', function (e) {
                e.preventDefault();
                $.ajax({
                    url: base_url + '/admin/package/' + $('[name=info_id]').val() + '/deletePackage',
                    method: "DELETE",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
                    },
                    data: {
                        "_token": "{{ csrf_token() }}",
                    },
                    success: function (response) {
                        location.reload();
                        // $('.api_error_message').html('<div class="alert alert-success alert-dismissible"> <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> <h4><i class="icon fa fa-ban"></i>Success!</h4>'+response.message+' </div>');

                    }
                })

            });


        })
    </script>
@endsection