routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/app/login', ['uses' => 'JwtAuthenticateController@appLogin', 'as' => 'app.login']);
Route::get('/app/logout', 'JwtAuthenticateController@logout')->name('app.logout');
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['ability:admin|destination,create-users'], 'as' => 'admin.'], function () {
    // Protected route
    Route::get('select_branch', 'DashboardController@selectBranch')->name('select_branch');
    Route::get('notifications/view_all', 'UserController@viewNotifications')->name('notification.view_all');
    Route::get('notifications/query', 'UserController@queryNotifications')->name('notification.query');
    Route::get('/bill-record', 'UserController@billRecord')->name('billRecord');
    Route::get('/bill-record/{id}/profile', 'UserController@billProfile')->name('bill_record.profile');
    Route::get('/bill-record/cancel', 'UserController@cancelBill')->name('billRecord.cancel');
    Route::post('/bill-record-store', 'UserController@storeBillRecord')->name('billRecord.store');
    Route::get('/bill-record-list', 'UserController@listBillRecord')->name('billRecord.list');
    Route::get('/bill-record-list/{id}/edit', 'UserController@editBillRecord')->name('billRecord.edit');
    Route::post('/bill-record-list/update', 'UserController@updateBillRecord')->name('billRecord.update');
    Route::get('/bill-record-list/delete', 'UserController@deleteBillRecord')->name('billRecord.delete');
    Route::get('dashboard', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);
    Route::post('/branch_para/import', 'BranchparaController@import')->name('branch_para.import');
    Route::resource('/branch_para', 'BranchparaController');
    Route::post('/package/updateDetail', 'UserController@updatePackage')->name('package.update_detail');
    Route::get('/package/{id}/edit', 'UserController@editPackage');
    Route::delete('/package/{id}/deletePackage', 'UserController@deletePackage');
    Route::get('/package', 'UserController@package')->name('package');
    Route::post('/package', 'UserController@packageStore')->name('package.store');
    Route::post('/category/updateDetail', 'UserController@updateItem')->name('category.update_detail');
    Route::get('/category/{id}/edit', 'UserController@editItem');
    Route::delete('/category/{id}/deleteItem', 'UserController@deletePackage');
    Route::get('/category', 'UserController@itemCategory')->name('category');
    Route::post('/category', 'UserController@itemCategoryStore')->name('category.store');
    Route::get('/user/add', 'UserController@addUser')->name('user.add');
     Route::get('/user/status_change', 'UserController@statusChange')->name('user.status_change');
    Route::get('/user/search_query','UserController@searchQuery')->name('user.search_query');
    Route::get('/user/profile/{id}','UserController@profile')->name('user.profile');
    Route::get('/user/member/selected', 'UserController@memberSelected')->name('user.member.selected');
    Route::post('/user/store', 'UserController@storeUser')->name('user.store');
    Route::get('/user/package/selected', 'UserController@selectedPackage')->name('user.package.selected');
    Route::get('/user/list', 'UserController@userList')->name('user.list');
    Route::get('/user/bill_detail/{id}', 'UserController@billDetail')->name('user.bill_detail');
    Route::get('/user/{id}/edit', 'UserController@editUser')->name('user.edit');
    Route::post('/user/updateDetail', 'UserController@updateUser')->name('user.updateDetail');
    Route::get('/user/cash_entry', 'UserController@cashEntry')->name('user.cash_entry');
    Route::post('/user/cash_entry', 'UserController@cashEntryPost')->name('user.cash_entry.store');
    Route::get('/user/cash_entry/list', 'UserController@cashEntryList')->name('user.cash_entry.list');
    Route::get('/user/cash_entry/list/{id}/edit', 'UserController@editCashEntryList')->name('user.cash_entry.list.edit');
    Route::post('/user/cash_entry/list/update', 'UserController@updateCashEntryList')->name('user.cash_entry.list.update');
    Route::get('/user/cash_entry/list/delete', 'UserController@deleteCashEntryList')->name('user.cash_entry.list.delete');
     Route::get('/user/cash_entry/monthlylist', 'UserController@monthlylist')->name('user.cash_entry.monthlylist');
    Route::post('/user/cash_entry/query', 'UserController@cashEntryQuery')->name('user.cash_entry.query');
    Route::get('/user/query', 'UserController@query')->name('user.query');
    Route::get('/user/bank_account', 'UserController@bankAccount')->name('user.bank_account');
    Route::post('/user/bank_account', 'UserController@bankEntryStore')->name('user.bank_account.store');
    Route::get('/user/bank_account/list', 'UserController@bankAccountList')->name('user.bank_account.list');
    Route::get('/user/bank_account/list/delete', 'UserController@deleteBankAccountList')->name('user.bank_account.list.delete');
    Route::get('/user/bank_account/list/{id}/edit', 'UserController@editBankAccountList')->name('user.bank_account.list.edit');
    Route::post('/user/bank_account/list/update', 'UserController@updateBankAccountList')->name('user.bank_account.list.update');
    Route::get('/user/bank_account/query', 'UserController@bankAccountQuery')->name('user.bank_account.queryList');
    Route::post('/user/bank_account/query', 'UserController@bankEntryQuery')->name('user.bank_account.query');
    Route::get('/user/valid_date','UserController@validDate')->name('user.valid_date');
    Route::group(['prefix' => 'utility', 'as' => 'utility.'], function () {
        Route::get('bill_issue', ['uses' => 'UtilityController@billIssueIndex', 'as' => 'bill_issue']);
        Route::post('bill_issue', ['uses' => 'UtilityController@billIssueStore', 'as' => 'bill_issue']);
    });
    Route::post('user/import','UserController@import')->name('user.import');


});

resources/views/admin/bill_record/edit.blade.php
@extends('admin.admin_layout.layout')
@section('content')
    <?php $token = Session::get('token'); ?>
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Bill Records
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Forms</a></li>
                <li class="active">General Elements</li>
            </ol>
        </section>
        <section class="content">
            <div class="row">

                <!-- left column -->
                <div class="col-md-12">
                    @include('flash.message')
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Edit</h3>
                        </div>

                        <form role="form" id="update_bill_record">
                            {!! csrf_field() !!}
                            <div class="box-body">
                                <input type="hidden" class="form-control"
                                       value="{{$bill_record->id}}" name="bill_id">
                                <br/>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="input-group input-group-sm">
                                                 <span class="input-group-btn">
                                                     <button type="button" class="btn btn-flat pwd_click">
                                                        Date
                                                    </button>
                                                 </span>
                                            <input type="text" id="datepicker2" class="form-control"
                                                   placeholder="Date" value="{{$bill_record->date}}" name="date" required>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="input-group input-group-sm">
                                                 <span class="input-group-btn">
                                                     <button type="button" class="btn btn-flat pwd_click">
                                                         Bill No.
                                                    </button>
                                                 </span>
                                            <input type="text" class="form-control"
                                                   value="{{$bill_record->bill_no}}" placeholder="Bill number" name="bill_no" required>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="input-group input-group-sm">
                                                 <span class="input-group-btn">
                                                     <button type="button" class="btn btn-flat pwd_click">
                                                         Name
                                                    </button>
                                                 </span>
                                            <input type="text" class="form-control"
                                                   value="{{isset($bill_record->member_name)?$bill_record->member_name:''}}" placeholder="Bill number" name="member_name" required>
                                        </div>
                                    </div>
                                </div>
                                <br>

                                <div class="row">
                                  <div class="col-md-4">
                                        <div class="input-group">
                                            <span class="input-group-addon">Membership No</span>
                                             <select name="membership_no" class="form-control dest_select_2">
                                                <option value="">Select Membership</option>
                                                <option value="">No member</option>
                                                @foreach($members as $m)
                                                    <option value="{{$m->membership_no}}" {{$m->membership_no==$bill_record->membership_no?'selected':''}}
                                                            required>{{$m->membership_no}}</option>
                                                @endforeach

                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="input-group">
                                            <label for="">Membership Name: </label>
                                                 <a href="{{route('admin.user.bill_detail',['membership_no'=>$bill_record->membership_no,'token'=>$token])}}" data-id="{{$bill_record->membership_no}}"
                                                   class="btn-delete">{{$bill_record->name}}</a>

                                        </div>
                                    </div>
                                    {{--<div class="col-md-4">--}}
                                    {{--<div class="input-group input-group-sm">--}}
                                    {{--<span class="input-group-btn">--}}
                                    {{--<button type="button" class="btn btn-flat pwd_click">--}}
                                    {{--Member Name--}}
                                    {{--</button>--}}
                                    {{--</span>--}}
                                    {{--<input type="text" class="form-control"--}}
                                    {{--placeholder="Member Name" name="member_name" required >--}}
                                    {{--</div>--}}
                                    {{--</div>--}}
                                    <div class="col-md-4">
                                        <div class="input-group">
                                            <span class="input-group-addon">Package</span>
                                            <select name="package" class="form-control" required>
                                                <option value="">--Select Package--</option>
                                                @foreach($packages as $p)
                                                    <option value="{{$p->month}}" {{$p->month==$bill_record->package?'selected':''}} required>{{$p->month}}</option>
                                                @endforeach

                                            </select>
                                        </div>
                                    </div>


                                </div>
                                <br/>
                                <div class="row">

                                    <div class="col-md-4">
                                        <div class="input-group">
                                            <span class="input-group-addon">Total Amount</span>
                                            <input type="number" class="form-control" placeholder="Amount"
                                                   value="{{$bill_record->amount}}" name="amount">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="input-group">
                                            <span class="input-group-addon">Paid Amount</span>
                                            <input type="number" class="form-control"placeholder="Paid Amount"
                                                   value="{{$bill_record->paid_amount}}" name="paid_amount">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="input-group">
                                            <span class="input-group-addon">Discount</span>
                                            <input type="number"  class="form-control" placeholder="Discount amt"
                                                   value="{{$bill_record->discount}}"  name="discount">
                                        </div>
                                    </div>


                                </div>
                                <br>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="input-group">
                                            <span class="input-group-addon">Due Amount</span>
                                            <input type="number" class="form-control" placeholder="Due Amount"
                                                   value="{{$bill_record->due_amount}}" name="due_amount">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="input-group">
                                            <span class="input-group-addon">Remarks</span>
                                            <input type="text" class="form-control" placeholder="Remarks"
                                                   value="{{$bill_record->remarks}}"  name="remarks">
                                        </div>
                                    </div>
                                </div>
                                <br>

                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
  <script>
      $('#update_bill_record').on('submit', function (e) {
          e.preventDefault();
          $.ajax({
              url: "{{route('admin.billRecord.update')}}",
              method: "POST",
              beforeSend: function (xhr) {
                  xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
              },
              data: $(this).serialize(),
              success: function (response) {
                  location.reload();
                  // $('.api_error_message').html('<div class="alert alert-success alert-dismissible"> <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> <h4><i class="icon fa fa-ban"></i>Success!</h4>'+response.message+' </div>');

              }
          })

      });
      $('.dest_select_2').on('select2:select', function (e) {
            console.log('test');
            var data = e.params.data;
            e.preventDefault();
            $.ajax({
                url: "{{route('admin.user.member.selected')}}",
                method: "GET",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
                },
                data: {
                    membership_no: $(this).val()

                },
                success: function (response) {
                    if (response.success == true) {
                        $('[name=member_name]').val(response.data.name);

                    }
                    // $('.api_error_message').html('<div class="alert alert-success alert-dismissible"> <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> <h4><i class="icon fa fa-ban"></i>Success!</h4>'+response.message+' </div>');


                }
            })
        });
      $('[name=package]').click(function (e) {
          e.preventDefault();
          $.ajax({
              url: "{{route('admin.user.package.selected')}}",
              method: "GET",
              beforeSend: function (xhr) {
                  xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
              },
              data: {
                  month: $(this).find('option:selected').val(),
                  admission_date: $("[name=date]").val()
              },
              success: function (response) {
                  if (response.success == false) {
                      $('[name=amount]').val("");
                      $('[name=user_valid_date]').val("");

                  }
                  console.log(response);
                  $('[name=amount]').val(response.data.price);
                  $('[name=user_valid_date]').val(response.data.user_valid_date);
                  // $('.api_error_message').html('<div class="alert alert-success alert-dismissible"> <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> <h4><i class="icon fa fa-ban"></i>Success!</h4>'+response.message+' </div>');


              }
          })

      });
      $('[name=amount],[name=discount],[name=paid_amount]').keyup(function () {

          var package_rate =  $('[name=amount]').val();
          var discount = $('[name=discount]').val();
          var paid_amt = $('[name=paid_amount]').val();
          var due_amt= package_rate-discount-paid_amt;
          $('[name=due_amount]').val(due_amt);

      })
  </script>

@endsection

resources/views/admin/bill_record/list.blade.php
@extends('admin.admin_layout.layout')
@section('content')
    <?php $token = Session::get('token'); ?>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Dashboard
                <small>Control panel</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                @include('flash.message');
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Bill Record Lists</h3>
                        </div>
                        <table id="example1" class="table table-responsive table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>SNo</th>
                                <th>Record Date</th>
                                <th>Membership No</th>
                                <th>Membership Name</th>
                                <th>Package</th>
                                <th>Bill No</th>
                                <th>Total Amount</th>
                                <th>Paid amount</th>
                                <th>Discount</th>
                                <th>Due Amount</th>
                                <th>Remarks</th>
                                <th>Valid Date</th>
                                <th>Created At</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $i = 1; ?>
                            @foreach($bill_records as $b)
                                <tr>
                                    <td>{{$i++}}</td>
                                    <td>{{$b->date}}</td>
                                    <td>{{$b->membership_no}} </td>
                                    <td><a href="{{route('admin.bill_record.profile',['id'=>$b->id,'token'=>$token])}}">{{$b->name}} </a></td>
                                    <td>{{$b->package}} </td>
                                    <td>{{$b->bill_no}} </td>
                                    <td>{{$b->amount}}</td>
                                    <td>{{$b->paid_amount}}</td>
                                    <td>{{$b->discount}}</td>
                                    <td>{{$b->due_amount}}</td>
                                    <td>{{$b->remarks}}</td>
                                    <td>@if(isset($b->valid_date)){{date("F j, Y", strtotime($b->valid_date))}}@endif</td>
                                    <td>{{date("F j, Y", strtotime($b->created_at))}}</td>
                                    <td>Status</td>
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn btn-default dropdown-toggle" type="button"
                                                    data-toggle="dropdown">Action
                                                <span class="caret"></span></button>
                                            <ul class="dropdown-menu">
                                                <li><a href="{{route('admin.billRecord.edit',['id'=>$b->id, 'token'=>$token])}}" data-id="{{$b->id}}" class="btn-edit">Edit</a>
                                                </li>
                                                <li><a href="#" data-id="{{$b->id}}"
                                                       class="btn-delete">Delete</a></li>
                                                <li><a href="#" data-id="{{$b->bill_no}}"
                                                       class="btn-cancel">Cancel</a></li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tfoot>
                        </table>
                    </div>
                </div>

            </div>

        </section>
    </div>
    <div id="myModal3" class="modal custom fade">
        <div class="modal-dialog" role="document">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete Information</h5>
                </div>
                <form id="delete_bill_record">
                    {!! csrf_field() !!}
                    <div class="modal-body">
                        <input name="record_id" type="hidden"/>

                        <p>Are you sure to delete this information?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Delete</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div id="cancelModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Cancellation Confirm</h4>
                </div>
                <div class="modal-body">
                    <input name="modal_bill_no" type="hidden"/>
                    <p>Are you sure you wanna ??.</p>
                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-default cancel_bill" value="cancel">Cancel</button>
                    <button type="button" class="btn btn-default cancel_bill" value="cancel_redo">Cancel And Redo</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>
    <script>
        <!--delete-->
        $('#example1').on('click', '.btn-delete', function (e) {
            var delete_id = $(this).attr('data-id');
            $('#myModal3').modal('show');
            $('[name="record_id"]').val(delete_id);

        });
        $('#example1').on('click', '.btn-cancel', function (e) {
            var data_id = $(this).attr('data-id');
            $('#cancelModal').modal('show');
            $('[name=modal_bill_no]').val(data_id);

        });
        $('.cancel_bill').click(function(){
            var type=$(this).val();
            $.ajax({
                url: "{{route('admin.billRecord.cancel')}}",
                method: "GET",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
                },
                data: {
                    bill_no:$('[name=modal_bill_no]').val(),
                    type:$(this).val()
                },
                success: function (response) {
                    // location.reload();
                    if(response.success == true){
                        if(type == 'cancel'){
                            location.reload();
                        }
                        else if(type=='cancel_redo'){
                            window.location.href="{{route('admin.billRecord',['token'=>$token])}}";
                        }
                    }
                    // $('.api_error_message').html('<div class="alert alert-success alert-dismissible"> <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> <h4><i class="icon fa fa-ban"></i>Success!</h4>'+response.message+' </div>');

                }
            })
        })
        $('#delete_bill_record').on('submit', function (e) {
            e.preventDefault();
            $.ajax({
                url: "{{route('admin.billRecord.delete')}}",
                method: "GET",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
                },
                data: $(this).serialize(),
                success: function (response) {
                    location.reload();
                    // $('.api_error_message').html('<div class="alert alert-success alert-dismissible"> <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> <h4><i class="icon fa fa-ban"></i>Success!</h4>'+response.message+' </div>');

                }
            })

        });
    </script>
@endsection