routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/app/login', ['uses' => 'JwtAuthenticateController@appLogin', 'as' => 'app.login']);
Route::get('/app/logout', 'JwtAuthenticateController@logout')->name('app.logout');
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['ability:admin|destination,create-users'], 'as' => 'admin.'], function () {
    // Protected route
    Route::get('select_branch', 'DashboardController@selectBranch')->name('select_branch');
    Route::get('notifications/view_all', 'UserController@viewNotifications')->name('notification.view_all');
    Route::get('notifications/query', 'UserController@queryNotifications')->name('notification.query');
    Route::get('/bill-record', 'UserController@billRecord')->name('billRecord');
    Route::get('/bill-record/{id}/profile', 'UserController@billProfile')->name('bill_record.profile');
    Route::get('/bill-record/cancel', 'UserController@cancelBill')->name('billRecord.cancel');
    Route::post('/bill-record-store', 'UserController@storeBillRecord')->name('billRecord.store');
    Route::get('/bill-record-list', 'UserController@listBillRecord')->name('billRecord.list');
    Route::get('/bill-record-list/{id}/edit', 'UserController@editBillRecord')->name('billRecord.edit');
    Route::post('/bill-record-list/update', 'UserController@updateBillRecord')->name('billRecord.update');
    Route::get('/bill-record-list/delete', 'UserController@deleteBillRecord')->name('billRecord.delete');
    Route::get('dashboard', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);
    Route::post('/branch_para/import', 'BranchparaController@import')->name('branch_para.import');
    Route::resource('/branch_para', 'BranchparaController');
    Route::post('/package/updateDetail', 'UserController@updatePackage')->name('package.update_detail');
    Route::get('/package/{id}/edit', 'UserController@editPackage');
    Route::delete('/package/{id}/deletePackage', 'UserController@deletePackage');
    Route::get('/package', 'UserController@package')->name('package');
    Route::post('/package', 'UserController@packageStore')->name('package.store');
    Route::post('/category/updateDetail', 'UserController@updateItem')->name('category.update_detail');
    Route::get('/category/{id}/edit', 'UserController@editItem');
    Route::delete('/category/{id}/deleteItem', 'UserController@deletePackage');
    Route::get('/category', 'UserController@itemCategory')->name('category');
    Route::post('/category', 'UserController@itemCategoryStore')->name('category.store');
    Route::get('/user/add', 'UserController@addUser')->name('user.add');
     Route::get('/user/status_change', 'UserController@statusChange')->name('user.status_change');
    Route::get('/user/search_query','UserController@searchQuery')->name('user.search_query');
    Route::get('/user/profile/{id}','UserController@profile')->name('user.profile');
    Route::get('/user/member/selected', 'UserController@memberSelected')->name('user.member.selected');
    Route::post('/user/store', 'UserController@storeUser')->name('user.store');
    Route::get('/user/package/selected', 'UserController@selectedPackage')->name('user.package.selected');
    Route::get('/user/list', 'UserController@userList')->name('user.list');
    Route::get('/user/bill_detail/{id}', 'UserController@billDetail')->name('user.bill_detail');
    Route::get('/user/{id}/edit', 'UserController@editUser')->name('user.edit');
    Route::post('/user/updateDetail', 'UserController@updateUser')->name('user.updateDetail');
    Route::get('/user/cash_entry', 'UserController@cashEntry')->name('user.cash_entry');
    Route::post('/user/cash_entry', 'UserController@cashEntryPost')->name('user.cash_entry.store');
    Route::get('/user/cash_entry/list', 'UserController@cashEntryList')->name('user.cash_entry.list');
    Route::get('/user/cash_entry/list/{id}/edit', 'UserController@editCashEntryList')->name('user.cash_entry.list.edit');
    Route::post('/user/cash_entry/list/update', 'UserController@updateCashEntryList')->name('user.cash_entry.list.update');
    Route::get('/user/cash_entry/list/delete', 'UserController@deleteCashEntryList')->name('user.cash_entry.list.delete');
     Route::get('/user/cash_entry/monthlylist', 'UserController@monthlylist')->name('user.cash_entry.monthlylist');
    Route::post('/user/cash_entry/query', 'UserController@cashEntryQuery')->name('user.cash_entry.query');
    Route::get('/user/query', 'UserController@query')->name('user.query');
    Route::get('/user/bank_account', 'UserController@bankAccount')->name('user.bank_account');
    Route::post('/user/bank_account', 'UserController@bankEntryStore')->name('user.bank_account.store');
    Route::get('/user/bank_account/list', 'UserController@bankAccountList')->name('user.bank_account.list');
    Route::get('/user/bank_account/list/delete', 'UserController@deleteBankAccountList')->name('user.bank_account.list.delete');
    Route::get('/user/bank_account/list/{id}/edit', 'UserController@editBankAccountList')->name('user.bank_account.list.edit');
    Route::post('/user/bank_account/list/update', 'UserController@updateBankAccountList')->name('user.bank_account.list.update');
    Route::get('/user/bank_account/query', 'UserController@bankAccountQuery')->name('user.bank_account.queryList');
    Route::post('/user/bank_account/query', 'UserController@bankEntryQuery')->name('user.bank_account.query');
    Route::get('/user/valid_date','UserController@validDate')->name('user.valid_date');
    Route::group(['prefix' => 'utility', 'as' => 'utility.'], function () {
        Route::get('bill_issue', ['uses' => 'UtilityController@billIssueIndex', 'as' => 'bill_issue']);
        Route::post('bill_issue', ['uses' => 'UtilityController@billIssueStore', 'as' => 'bill_issue']);
    });
    Route::post('user/import','UserController@import')->name('user.import');


});

app/User.php
<?php

namespace App;

use Zizaco\Entrust\Traits\EntrustUserTrait;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Auth;

class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','category'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function userData()
    {
        return $this->belongsTo('App\Models\Admin\EmployeeParameter', 'id', 'user_id');
    }

    public static function userPermissionCan($permission)
    {
        $check_permission = UserPermission::where('user_id', '=', Auth::user()->id)
            ->join('permissions as p', 'p.id', '=', 'permission_user.permission_id')
            ->where('p.name', '=', $permission)
            ->first();
        if ($check_permission)
            return true;
        return false;
    }
//    public function language()
//    {
//        return $this->belongsTo('App\Models\Admin\EmployeeParameter');
//    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Admin\BillsRecord;
use App\Models\Admin\CashBook;
use App\Models\Admin\Company;
use App\Models\Admin\CountryPara;
use App\Models\Admin\CustomerDetail;
use App\Models\Admin\CustomerPara;
use App\Models\Admin\CustomerPriceDetail;
use App\Models\Admin\EmployeeParameter;
use App\Models\Admin\Member;
use App\Models\Admin\MerchandisePara;
use App\Models\Admin\Notifications;
use App\Models\Admin\Package;
use App\Models\Admin\ZoneMaster;
use App\Permission;
use App\RolePermission;
use App\UserPermission;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use App\User;
use App\Role;
use Hash;
use App\Models\Admin\LocationHierarachy;
use App\Models\Admin\BranchPara;
use Input;
use Excel;
use App;
use Session;
use Illuminate\Support\Collection;
use App\Models\Admin\BillStockPara;
use  App\Repositories\Backend\BranchPara\BranchParaInterface;
use App\Models\Admin\BankAccount;
use App\Models\Admin\Item;

class UserController extends DashboardController
{
    public function __construct(BranchParaInterface $branch_para)
    {
        parent::__construct();
        $this->branch_para = $branch_para;
    }

    public function customerIndex()
    {

        Session::forget('function_type_b');
        Session::forget('function_type_a');
        $this->admin_data['customer_paras'] = CustomerPara::orderBy('id', 'desc')->where('branch_code', '=', $this->admin_data['login_user']->branch_code)->get();
        $this->admin_data['master_companies'] = Company::all();
        $this->admin_data['country_para'] = CountryPara::orderBy('country_name', 'desc')->get();
        $this->admin_data['branch_para'] = BranchPara::where('branch_code', '=', $this->admin_data['login_user']->branch_code)->first();
        return view('admin.user.customer.index', $this->admin_data);
    }

    public function package()
    {
        $this->admin_data['packages'] = Package::orderby('id', 'desc')->where('category','=',$this->admin_data['login_user']->category)->get();
        return view('admin.package.index', $this->admin_data);
    }

    public function packageStore(Request $request)
    {
        $data=$request->all();
        $data['category']=$this->admin_data['login_user']->category;
        Package::create($data);
        Session::flash('successMsg', 'Package saved successfully');
        return response()->json(['success' => 'true'], 200);
    }

    public function selectedPackage(Request $request)
    {
        if ($request->month == null)
            return response()->json(['success' => false], 200);
        if($request->month=='Due'){
            $bill_record=BillsRecord::where('membership_no','=',$request->membership_no)->where('due_amount','!=',0)->orderBy('id','desc')->first();
            return response()->json(['success' => true, 'message' => '', 'data' => ['price' => $bill_record->due_amount, 'user_valid_date' => $bill_record->valid_date]], 200);
        }
        $month = Package::where('month', '=', $request->month)->where('category','=',$this->admin_data['login_user']->category)->first();
        $time = strtotime($request->admission_date);
        if($request->valid_date_change_type=='User Old Date'){
            $date=BillsRecord::where('membership_no','=',$request->membership_no)->orderBy('id','desc')->first();
            $time=strtotime($date->valid_date);
        }
        $user_valid_date = date("Y-m-d", strtotime("+" . $request->month . " month", $time));
        return response()->json(['success' => true, 'message' => '', 'data' => ['price' => $month->price, 'user_valid_date' => $user_valid_date]], 200);
    }

    public function validDate(Request $request)
    {
        $time = strtotime($request->admission_date);
        $user_valid_date = date("Y-m-d", strtotime("+24 month", $time));
        return response()->json(['success' => true, 'message' => '', 'data' => ['user_valid_date' => $user_valid_date]], 200);

    }


    public function deletePackage($id)
    {
        $package = Package::find($id);
        $package->delete();
        Session::flash('successMsg', 'Package deleted successfully');
        return response()->json(['success' => true, 'message' => 'Package Deleted', 'data' => null], 200);
    }

    public function editPackage($id)
    {
        $package = Package::find($id);
        return response()->json(['success' => true, 'message' => 'Package Editted', 'data' => ['package' => $package]], 200);
    }

    public function updatePackage(Request $request)
    {
        Package::where('id', '=', $request->package_id)->update(['month' => $request->month_pop, 'price' => $request->price_pop]);
//        $package =Package::find($id);
        Session::flash('successMsg', 'Package updated successfully');
        return response()->json(['success' => true, 'message' => 'Package Deleted', 'data' => null], 200);

    }
    public function deleteItem($id)
    {
        $item = Item::find($id);
        $item->delete();
        Session::flash('successMsg', 'Package deleted successfully');
        return response()->json(['success' => true, 'message' => 'Package Deleted', 'data' => null], 200);
    }

    public function editItem($id)
    {
        $item = Item::find($id);
        return response()->json(['success' => true, 'message' => 'Package Editted', 'data' => ['item' => $item]], 200);
    }

    public function updateItem(Request $request)
    {
        Item::where('id', '=', $request->item_id)->update(['item_name' => $request->item_name, 'price' => $request->price]);
//        $package =Package::find($id);
        Session::flash('successMsg', 'Package updated successfully');
        return response()->json(['success' => true, 'message' => 'Package Deleted', 'data' => null], 200);

    }
    public function itemCategory()
    {
        $this->admin_data['items'] =Item::orderby('id', 'desc')->get();
        return view('admin.category.index', $this->admin_data);
    }

    public function itemCategoryStore(Request $request)
    {
        $data=$request->all();
//        $data['category']=$this->admin_data['login_user']->category;
        Item::create($data);
        Session::flash('successMsg', 'Package saved successfully');
        return response()->json(['success' => 'true'], 200);
    }


    public function billProfile($id){
        $this->admin_data['bill_record'] = BillsRecord::select('members.*', 'bills_record.*')
            ->leftJoin('members', 'members.membership_no', '=', 'bills_record.membership_no')
            ->where('bills_record.id','=',$id)
            ->orderBy('bills_record.id', 'desc')
            ->first();
        $now = time(); // or your date as well
        $your_date = strtotime($this->admin_data['bill_record']->valid_date);
        $datediff = $your_date- $now;

        $this->admin_data['date_diff']=(round($datediff / (60 * 60 * 24)));
      return view('admin.bill_record.bill_profile',$this->admin_data);
    }
    public function billRecord()
    {
//        $bill = BillStockPara::orderBy('id', 'desc')->first();

//        $length = strlen($bill->prefix);
//        $query = BillsRecord::select(DB::raw("MAX(CAST(SUBSTRING(bill_no," . $length . "+1) AS UNSIGNED)+1) AS bill_no"))->whereRaw("SUBSTRING(bill_no,1," . $length . ") ='" . $bill->prefix . "'")->first();
//        if ($query->bill_no != null) {
//            $this->admin_data['bill_no'] = $bill->prefix . $query->bill_no;
//        } else {
//            $this->admin_data['bill_no'] = $bill->prefix . '1';
//        }
        $length = 0;
        $query = BillsRecord::select(DB::raw("MAX(CAST(SUBSTRING(bill_no," . $length . "+1) AS UNSIGNED)+1) AS bill_no"))->first();
        if ($query->bill_no != null) {

            $this->admin_data['bill_no'] = $query->bill_no;
        } else {
            $this->admin_data['bill_no'] = 1;
        }
        $this->admin_data['packages']=Package::where('category','=',$this->admin_data['login_user']->category)->get();
        $this->admin_data['members'] = Member::all();
        if($this->admin_data['login_user']->category=='fitness'){
            $this->admin_data['items']=Item::all();
        }
        return view('admin.bill_record.index', $this->admin_data);
    }

    public function cancelBill(Request $request)
    {
        BillsRecord::where('bill_no', '=', $request->bill_no)->update(['status' => 'Cancelled']);
        Session::flash('successMsg', 'Bill NO succesfully cancelled');
        return response()->json(['success' => true], 200);
    }

    public function storeBillRecord(Request $request)
    {
        $bil_record = new BillsRecord();
        $bil_record->date = isset($request->date) ? $request->date : '0';
        $bil_record->membership_no = isset($request->membership_no) ? $request->membership_no : '';
        $bil_record->name = isset($request->member_name) ? $request->member_name : '';
//        $query = BillsRecord::select(DB::raw("MAX(bill_no)+1 AS bill_no"))->first();
//        if ($query->bill_no != null) {
        $bil_record->bill_no = $request->bill_no;
//        } else {
//            $bil_record->bill_no = 1;
//        }
        if($request->package =='Due'){
            $bill_record=BillsRecord::where('membership_no','=',$request->membership_no)->where('due_amount','!=',0)->orderBy('id','desc')->first();
            $bill_record->due_amount=0;
            $bill_record->save();
        }
        $bil_record->package = isset($request->package) ? $request->package : '0';
        $bil_record->amount = isset($request->amount) ? $request->amount : '0';
        $bil_record->discount = isset($request->discount) ? $request->discount : '0';
        $bil_record->paid_amount = isset($request->paid_amount) ? $request->paid_amount : '0';
        $bil_record->due_amount = isset($request->due_amount) ? $request->due_amount : '0';
        $bil_record->remarks = isset($request->remarks) ? $request->remarks : '';

resources/views/admin/user/list.blade.php
@extends('admin.admin_layout.layout')
@section('content')
    <?php $token = Session::get('token'); ?>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Dashboard
                <small>Control panel</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
            @include('flash.message')
            <!-- left column -->

                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Member List</h3>
                        </div>
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Membership NO</th>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Admission Date</th>
                                <th>User Valid Date</th>
                                <th>Contact</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $i = 1; ?>
                            @foreach($members as $p)
                                <tr>
                                    <td><a href="{{route('admin.user.profile',['id'=>$p->id,'token'=>$token])}}">{{$p->membership_no}}</a></td>
                                    <td><a href="{{route('admin.user.profile',['id'=>$p->id,'token'=>$token])}}">{{$p->name}}</a></td>
                                    <td>{{$p->address}}</td>
                                    <td>{{$p->admission_date}}</td>
                                    <td>{{$p->user_valid_date}}</td>
                                    <td>{{$p->contact}}</td>
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn btn-default dropdown-toggle" type="button"
                                                    data-toggle="dropdown">Action
                                                <span class="caret"></span></button>
                                            <ul class="dropdown-menu">
                                                <li><a href="{{route('admin.user.edit',['id'=>$p->membership_no,'token'=>$token])}}" data-id="{{$p->id}}" class="btn-edit">Edit</a>
                                                </li>
                                                {{--<li><a href="#" data-id="{{$p->id}}"--}}
                                                       {{--class="btn-delete">Delete</a></li>--}}
                                                <li><a href="{{route('admin.user.bill_detail',['membership_no'=>$p->membership_no,'token'=>$token])}}" data-id="{{$p->membership_no}}"
                                                       class="btn-delete">View bill Detail</a></li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tfoot>
                        </table>
                    </div>
                </div>
                <!--/.col (left) -->
                <!-- right column -->

                <!--/.col (right) -->
            </div>

        </section>
    </div>
    <!-- Modal -->

    <div id="myModal2" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="edit-branch">
                    <div class="box box-primary">
                        <form role="form" id="update_package">
                            {!! csrf_field() !!}
                            <div class="box-header with-border">
                                <h3 class="box-title">Edit Package</h3>
                            </div>
                            <div class="box-body">
                                <input name="package_id" type="hidden">
                                <div class="input-group ">
                                    <select name="month_pop" class="form-control">
                                        @for($i=1;$i<27;$i++)
                                            <option value="{{$i}}" required>{{$i}}</option>
                                        @endfor
                                    </select>
                                    <span class="input-group-addon">Month</span>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Price</label>
                                    <input type="text" class="form-control" id="exampleInputPassword1"
                                           placeholder="Price"
                                           name="price_pop" required>
                                </div>
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div id="myModal3" class="modal custom fade">
        <div class="modal-dialog" role="document">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete Information</h5>
                </div>
                <form action="#" method="Post" id="delete_package">
                    {!! csrf_field() !!}
                    <div class="modal-body">
                        <input name="info_id" type="hidden"/>

                        <p>Are you sure to delete this information?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Delete</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            var base_url = "{{url('/')}}";
            <!--edit-->
            $('#example1').on('click', '.btn-edit', function () {
                $.ajax({
                    url: base_url + '/admin/package/' + $(this).attr('data-id') + '/edit',
                    method: "GET",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
                    },
                    data: $(this).serialize(),
                    success: function (response) {
                        $('#myModal2').modal('show');
                        $('option:selected', 'select[name="month_pop"]').removeAttr('selected');
                        $('[name="month_pop"]').find('option[value=' + response.data.package.month + ']').attr('selected', 'selected');
                        $('[name="price_pop"]').val(response.data.package.price);
                        $('[name="package_id"]').val(response.data.package.id);
                    }
                })
            });
            $('#update_package').submit(function (e) {
                e.preventDefault();
                $.ajax({
                    url: "{{route('admin.package.update_detail')}}",
                    method: "POST",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
                    },

                    data: $(this).serialize(),
                    success: function (response) {
                        location.reload();
                    }

                })
            });

            $('#branch_para_submit').submit(function (e) {
                e.preventDefault();
                $.ajax({
                    url: "{{route('admin.package.store')}}",
                    method: "POST",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
                    },
                    data: $(this).serialize(),
                    success: function (response) {
                        console.log(response);
                        location.reload();
                        // $('.api_error_message').html('<div class="alert alert-success alert-dismissible"> <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> <h4><i class="icon fa fa-ban"></i>Success!</h4>'+response.message+' </div>');


                    }
                })
            });
            $('#branch_para_submit').keyup(function (event) {

                if (event.keyCode === 112) {
                    $('.submit_click').click();

                }
            });

            <!--delete-->
            $('#example1').on('click', '.btn-delete', function (e) {
                var delete_id = $(this).attr('data-id');
                $('#myModal3').modal('show');
                $('[name="info_id"]').val(delete_id);

            });
            $('#delete_package').on('submit', function (e) {
                e.preventDefault();
                $.ajax({
                    url: base_url + '/admin/package/' + $('[name=info_id]').val() + '/deletePackage',
                    method: "DELETE",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('Authorization', 'Bearer ' + "{{$token}}");
                    },
                    data: {
                        "_token": "{{ csrf_token() }}",
                    },
                    success: function (response) {
                        location.reload();
                        // $('.api_error_message').html('<div class="alert alert-success alert-dismissible"> <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> <h4><i class="icon fa fa-ban"></i>Success!</h4>'+response.message+' </div>');

                    }
                })

            });


        })
    </script>
@endsection