routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/app/login', ['uses' => 'JwtAuthenticateController@appLogin', 'as' => 'app.login']);
Route::get('/app/logout', 'JwtAuthenticateController@logout')->name('app.logout');
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['ability:admin|destination,create-users'], 'as' => 'admin.'], function () {
    // Protected route
    Route::get('select_branch', 'DashboardController@selectBranch')->name('select_branch');
    Route::get('notifications/view_all', 'UserController@viewNotifications')->name('notification.view_all');
    Route::get('notifications/query', 'UserController@queryNotifications')->name('notification.query');
    Route::get('/bill-record', 'UserController@billRecord')->name('billRecord');
    Route::get('/bill-record/{id}/profile', 'UserController@billProfile')->name('bill_record.profile');
    Route::get('/bill-record/cancel', 'UserController@cancelBill')->name('billRecord.cancel');
    Route::post('/bill-record-store', 'UserController@storeBillRecord')->name('billRecord.store');
    Route::get('/bill-record-list', 'UserController@listBillRecord')->name('billRecord.list');
    Route::get('/bill-record-list/{id}/edit', 'UserController@editBillRecord')->name('billRecord.edit');
    Route::post('/bill-record-list/update', 'UserController@updateBillRecord')->name('billRecord.update');
    Route::get('/bill-record-list/delete', 'UserController@deleteBillRecord')->name('billRecord.delete');
    Route::get('dashboard', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);
    Route::post('/branch_para/import', 'BranchparaController@import')->name('branch_para.import');
    Route::resource('/branch_para', 'BranchparaController');
    Route::post('/package/updateDetail', 'UserController@updatePackage')->name('package.update_detail');
    Route::get('/package/{id}/edit', 'UserController@editPackage');
    Route::delete('/package/{id}/deletePackage', 'UserController@deletePackage');
    Route::get('/package', 'UserController@package')->name('package');
    Route::post('/package', 'UserController@packageStore')->name('package.store');
    Route::post('/category/updateDetail', 'UserController@updateItem')->name('category.update_detail');
    Route::get('/category/{id}/edit', 'UserController@editItem');
    Route::delete('/category/{id}/deleteItem', 'UserController@deletePackage');
    Route::get('/category', 'UserController@itemCategory')->name('category');
    Route::post('/category', 'UserController@itemCategoryStore')->name('category.store');
    Route::get('/user/add', 'UserController@addUser')->name('user.add');
     Route::get('/user/status_change', 'UserController@statusChange')->name('user.status_change');
    Route::get('/user/search_query','UserController@searchQuery')->name('user.search_query');
    Route::get('/user/profile/{id}','UserController@profile')->name('user.profile');
    Route::get('/user/member/selected', 'UserController@memberSelected')->name('user.member.selected');
    Route::post('/user/store', 'UserController@storeUser')->name('user.store');
    Route::get('/user/package/selected', 'UserController@selectedPackage')->name('user.package.selected');
    Route::get('/user/list', 'UserController@userList')->name('user.list');
    Route::get('/user/bill_detail/{id}', 'UserController@billDetail')->name('user.bill_detail');
    Route::get('/user/{id}/edit', 'UserController@editUser')->name('user.edit');
    Route::post('/user/updateDetail', 'UserController@updateUser')->name('user.updateDetail');
    Route::get('/user/cash_entry', 'UserController@cashEntry')->name('user.cash_entry');
    Route::post('/user/cash_entry', 'UserController@cashEntryPost')->name('user.cash_entry.store');
    Route::get('/user/cash_entry/list', 'UserController@cashEntryList')->name('user.cash_entry.list');
    Route::get('/user/cash_entry/list/{id}/edit', 'UserController@editCashEntryList')->name('user.cash_entry.list.edit');
    Route::post('/user/cash_entry/list/update', 'UserController@updateCashEntryList')->name('user.cash_entry.list.update');
    Route::get('/user/cash_entry/list/delete', 'UserController@deleteCashEntryList')->name('user.cash_entry.list.delete');
     Route::get('/user/cash_entry/monthlylist', 'UserController@monthlylist')->name('user.cash_entry.monthlylist');
    Route::post('/user/cash_entry/query', 'UserController@cashEntryQuery')->name('user.cash_entry.query');
    Route::get('/user/query', 'UserController@query')->name('user.query');
    Route::get('/user/bank_account', 'UserController@bankAccount')->name('user.bank_account');
    Route::post('/user/bank_account', 'UserController@bankEntryStore')->name('user.bank_account.store');
    Route::get('/user/bank_account/list', 'UserController@bankAccountList')->name('user.bank_account.list');
    Route::get('/user/bank_account/list/delete', 'UserController@deleteBankAccountList')->name('user.bank_account.list.delete');
    Route::get('/user/bank_account/list/{id}/edit', 'UserController@editBankAccountList')->name('user.bank_account.list.edit');
    Route::post('/user/bank_account/list/update', 'UserController@updateBankAccountList')->name('user.bank_account.list.update');
    Route::get('/user/bank_account/query', 'UserController@bankAccountQuery')->name('user.bank_account.queryList');
    Route::post('/user/bank_account/query', 'UserController@bankEntryQuery')->name('user.bank_account.query');
    Route::get('/user/valid_date','UserController@validDate')->name('user.valid_date');
    Route::group(['prefix' => 'utility', 'as' => 'utility.'], function () {
        Route::get('bill_issue', ['uses' => 'UtilityController@billIssueIndex', 'as' => 'bill_issue']);
        Route::post('bill_issue', ['uses' => 'UtilityController@billIssueStore', 'as' => 'bill_issue']);
    });
    Route::post('user/import','UserController@import')->name('user.import');


});

resources/views/Authentication/login.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Patan | GYM</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{url('bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{url('bower_components/font-awesome/css/font-awesome.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{url('bower_components/Ionicons/css/ionicons.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{url('dist/css/AdminLTE.min.css')}}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{url('plugins/iCheck/square/blue.css')}}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="../../index2.html"><b>Patan</b>Gym</a>
    </div>
    <div class="api_error_message"></div>
@include('flash.message')
    <!-- /.login-logo -->
    <div class="login-box-body">

        <p class="login-box-msg">Sign in to start your session</p>

        <form action="" method="post" id="app_login">
            <div class="form-group has-feedback">
                <input type="email" name="email" class="form-control" placeholder="Email">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" name="password" class="form-control" placeholder="Password">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox"> Remember Me
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                </div>
                <!-- /.col -->
            </div>
        </form>

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{{url('bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{url('bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- iCheck -->
<script src="{{url('plugins/iCheck/icheck.min.js')}}"></script>
<script>
    var api_url="{{route('app.authenticate')}}";
    var success_url="{{route('admin.dashboard')}}";
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
</script>
<script src="{{url('js/login_api.js')}}"></script>
</body>
</html>